### ISSUE TITLE
datetime.datetime error in "Python: part 3" documentation!

### ISSUE THREAD

**Issue by loujemouse** [jhill1/SEPwC.github.io#13]
Some sample code in the SEPwC documentation, Page "[Python: part 3](https://jhill1.github.io/SEPwC.github.io/Python3.html#)" throws a error in the python interpreter and does not output the current time. This is due to the `datetime.datetime.now()` function having a typo in it. The error shown is in screenshots 1 & 2.

Here are some alternatives:

shown in screenshot 3: 
`import datetime`
`now = datetime.now()` 
`print (now)`

or, a more condensed version (screenshot 4):
`from datetime import datetime`
`print(datetime.now())`

![Datetime error1](https://github.com/jhill1/SEPwC.github.io/assets/136651356/bdd4349c-e8c5-429c-a411-d604c91bef07)
**^ Attachment 1 (code throwing error)**

![Datetime error2](https://github.com/jhill1/SEPwC.github.io/assets/136651356/b7ed7019-a8f2-4cb5-a548-7c9a13d96a5a)
**^ Attachment 2 (code throwing error)**

![Datetime error3](https://github.com/jhill1/SEPwC.github.io/assets/136651356/23882ab7-3e98-470f-8a44-d0674f597fba)
**^ Attachment 3 (code solution 1)**

![Datetime error4](https://github.com/jhill1/SEPwC.github.io/assets/136651356/a211fb73-a80e-41e4-ab02-d4a0eedfb2ab)
**^ Attachment 4 (code solution 2)**

**Comment by jhill1** [comment]
Fixed.
